### ISSUE TITLE
Encore Example for TYPO3

### ISSUE THREAD

**Issue by FaraFara** [sabbelasichon/typo3_encore#1]
Hi!
Great job!

May you post actual TYPO3 encore example?

Thanx!

**Comment by sabbelasichon** [comment]
@FaraFara 
What do you need? It is actually all part of Webpack Encore. Have a look at their documentation and use every thing they do. The integration in TYPO3 itself is fairly simple/transparent. Just point to the entrypoints.json and manifest.json and include the files by EntryName. But of course, if you like i could do kickstart Example.

**Comment by sabbelasichon** [comment]
@FaraFara Did you try it out?

**Comment by FaraFara** [comment]
Please, provide a kickstart example.

**Comment by sabbelasichon** [comment]
@FaraFara I have extended the README how install the frontend stuff: https://github.com/sabbelasichon/typo3_encore#getting-started-with-webpack-encore

This should help to get started.

**Comment by sabbelasichon** [comment]
@FaraFara 

Would really like to know, if you succeed in using a setup.
