### ISSUE TITLE
Add option to select assets for http/2 push

### ISSUE THREAD

**Issue by moe2k** [sabbelasichon/typo3_encore#10]
In current dev-master, **all** entry point files are being pushed. However, if I use different entry points on one page, for example one which is critical and another one which is not, I would like an option to select which assets shall be pushed. Another use case is that I might want css to be pushed but not js. 

So maybe an option to enable/disable pushing for an asset would be nice. This could be achieved by defining a boolean, e.g. `enableHttp2Push` (which defaults to true) that can be passed as "false" to `additionalParameters` in the ViewHelper to disable it.

**Comment by moe2k** [comment]
Thanks, Assets managed by typo3-encore can now be left out from push if configured.

However I am wondering that now there seems to be a new feature which even adds asset files which are NOT managed by typo3-encore, right? For example files added to the page using typoscript methods like `page.includeCSS`) etc. are also included in the push header, so I end up again not being able to leave them out from push... ;-)

**Comment by sabbelasichon** [comment]
@moe2k This should not be the case. If you add a file with page.includeCSS and this is not prefixed with typo3_encore then no this is not part of the push header. Would be surprised if this is the case. 

But you are right, at the moment the exclusion is only possible for the ViewHelper and not for the assets included via TypoScript.
