### ISSUE TITLE
TagRenderer throws exception (warning) in PHP 8

### ISSUE THREAD

**Issue by TheNaderio** [sabbelasichon/typo3_encore#111]
```
PHP Warning: Undefined array key "doctype" in /var/www/html/public/typo3conf/ext/typo3_encore/Classes/Asset/TagRenderer.php line 253
```

The Problem is already solved in dev-master, but not released.

Is there anything that should be tested for PHP 8 where I can eventually help to speed up the new version release?

**Comment by sabbelasichon** [comment]
I am gonna release the new version this evening

**Comment by hardanders-dev** [comment]
thank you @sabbelasichon!  🎉

**Comment by sabbelasichon** [comment]
version 4.0.0 was released. It is a major version because i have changed some contracts. Probably rarely used, but let´s be serious about semver.
