### ISSUE TITLE
A question regarding static asset processing

### ISSUE THREAD

**Issue by fpodschwadek** [sabbelasichon/typo3_encore#123]
First, many thanks for this extension, it's a great links between the TYPO3 world and modern asset handling with Webpack.

I have one question regarding static assets, e.g., images. The docs show an example that makes use of the Webpack Encore `copyFiles` function (https://github.com/sabbelasichon/typo3_encore#creating-the-webpackconfigjs-file), including the possibility to use version hashes for the output files.

And while static assets appear as expected in the manifest, I cannot figure out how to include them directly in a fluid template. I would think there has to be a ViewHelper for that but could not find anything.

Any advice would be much appreciated.

**Comment by sabbelasichon** [comment]
@fpodschwadek You are welcome. Glad you like it. I think what you are looking for is the AssetViewHelper. https://github.com/sabbelasichon/typo3_encore/blob/master/Classes/ViewHelpers/AssetViewHelper.php

It is not quite as magical as you would expect. Just provide the name of the build / package. Normally the default one that´s also the default and the path to the file. 

```html
<encore:asset pathToFile="EXT:my_extension/Resources/Public/Build/images/asset.png" />
```

The version hash is added behind the scenes if needed. Hope that helps. If you like you could also add a PR for the documentation so anyone can benefit from it.

**Comment by fpodschwadek** [comment]
Splendid, thank you.

I will add a PR request for docs update later.
