### ISSUE TITLE
CSS for multiple RTE fields does not work

### ISSUE THREAD

**Issue by rvock** [sabbelasichon/typo3_encore#126]
When editing a TCA table with multiple RTE fields which all have the same CSS, only the first field will get the CSS.

This happens because the method `EntryPointLookup->getCssFiles` only returns the files the first time it is called. The second time nothing is returned. This is the same in Symfony.
The RTE feature was introduced with #116.

I think a simple fix would be to cache the result of the `getCssFiles()` within `RichtextEncoreConfiguration`.

**Comment by rvock** [comment]
Yes, the `reset()` method works as well and is a much easier fix. I will update the pull-request.

**Comment by sabbelasichon** [comment]
@rvock I have fixed it. Thank you very much.
