### ISSUE TITLE
Multiple Entrypoint.json

### ISSUE THREAD

**Issue by bernhardberger** [sabbelasichon/typo3_encore#13]
Maybe it is a conceptional problem on my part, but I have the following scenario:

I use Webpack Encore + Vue in some Backend Modules - in different standalone extensions. Right now I have to resort to squashing everything into one entry file (let's say mymodule.js and render that using the Page Renderer in my BE Module and I have to include a <script> Tag for the dev-server eith HMR as the PageRenderer struggles with http:// includes).

I'd love to use typo3_encore for this, but I already use it for my Frontend Build and therefore already have an entrypoints.json somewhere.

I can't include the BE sources in this as they are basically microbuilds for every different BE module.

It would therefore be awesome if I could specify multiple entrypoint.json instead of the single one in the constants. Then I could use typo3_encore to render my specific module entrypoints/manifests..

Am I missing something or could this be a useful feature request?

**Comment by sabbelasichon** [comment]
@bernhardberger Hi, this is already possible, but not well documented. You can create multiple builds. Have a look at https://github.com/sabbelasichon/typo3_encore#additional and https://symfony.com/doc/current/frontend/encore/advanced-config.html#defining-multiple-webpack-configurations. Hope that helps

**Comment by bernhardberger** [comment]
I think I may have not been clear:

I need to have my extension vue js backend stuff work independently from my "global" project webpack config.

I want (need) to build and bundle my entry js within the extension itself.

typo3conf/ext/my_module_one/build/entrypoints.json
typo3conf/ext/my_module_two/build/entrypoints.json

**Comment by sabbelasichon** [comment]
Have to think about it. 

But at the moment i had only one webpack.config.js with multiple different builds. You can specify then where to output the different builds. In every build folder you have all the dependencies and also the entrypoints.json file for this specific build. In the extension you can define where to lookup the different builds and you can also specify in the ViewHelper the build you want to use. I will update the README.md to make this concept clearer. Will happen tonight.

**Comment by bernhardberger** [comment]
Yeah, I do get that concept. But that also means I'd have to maintain a separate webpack config for every single main TYPO3 website project I intend to use my BE module for.

Whilst I'd be kind of fine doing that for FE related stuff, it would mean every time I change something in the BE module build I'd have to rebuild projects in the double-digits and re-deploy them instead of just deploying an updated extension build - if I want to use features like splitEntryChunks or lazyloading imports.

I'd kind if need "scoped instances of typo3_encore" if that makes any sense..

**Comment by sabbelasichon** [comment]
First of all, thanks for your kind words. I really love to hear from people what they think, what can be improved etc. Thank you very much. 

If if get it right, you already build the so called dist folder in your different Backend extensions. If so, you can just teach typo3_encore to lookup in different build directories. Your different backend extensions are in fact just different build directories. So you can just setup the build configurations and then include it via typo3_encore:buildOfBackendExtensionOne:app

`plugin.tx_typo3encore {
    settings {
        builds {
            firstBuild = EXT:typo3_encore/Resources/Public/FirstBuild
            buildOfBackendExtensionOne = EXT:my_ext/build/
        }
    }
}`

**Comment by bernhardberger** [comment]
Ah, okay. So that basically ignores the entrypoints/manifest json set via constants/setup? 

If so, then why not just scrap that setting altogether?

**Comment by sabbelasichon** [comment]
Yes, exactly. It is totally ignored then. 

The reason is for backwards compatibility and ease of use. But, yes you are otherwise totally right. Will think about it, if i should break this for the next major release. 

If you are happy and everything works for you, please close this issue.

**Comment by bernhardberger** [comment]
Yep, works like a charm with the `builds` setting.

You could still use the constants for a `default` or `fallback` build in setup.typoscript, but that setting was actually the one that caused confusion.
