### ISSUE TITLE
TYPO3 8.7 - Error in BackendModule (or nothing included, depending on method)

### ISSUE THREAD

**Issue by bernhardberger** [sabbelasichon/typo3_encore#14]
When I try to include js/css via EXT:typo3_encore in a BackendModule I get the following error (TYPO3 8.7):

```
#1476107295: PHP Warning: file_get_contents(/var/www/html/htdocs/typo3/typo3temp/assets/compressed/external-77c5661ecec798f0ac007291224fa800): failed to open stream: No such file or directory in /var/www/html/vendor/typo3/cms/typo3/sysext/core/Classes/Resource/ResourceCompressor.php line 287 (More information)
```

Happens using any of the methods mentioned below:
```xml
<f:be.container
        includeCssFiles="{0: 'typo3_encore:tx_myext_backendModule:backend-module'}"
        includeJsFiles="{0: 'typo3_encore:tx_myext_backendModule:backend-module'}">

</f:be.container>
```
and
```php
$pageRenderer->addJsFooterFile('typo3_encore:tx_myext_backendModule:backend-module')
```

If I try to include it using the ViewHelpers - nothing at all gets included:
```xml
<e:renderWebpackScriptTags entryName="backend-module" buildName="tx_myext_backendModule"></e:renderWebpackScriptTags>
```

TypoScript Setup (ext_typoscript_setup.txt):

```
module.tx_typo3encore {
	settings {
		builds {
			tx_myext_backendModule = EXT:my_ext/Resources/Public/Build
		}
	}
}
```

It does try to look it up, when I set an invalid build name or entryPoint the extension throws an exception like expected.

Any ideas?

**Comment by bernhardberger** [comment]
Actually, If I include it directly via PageRenderer and exclude it from concatenation it also doesn't include anything: 
```
$pageRenderer->addJsFooterFile('typo3_encore:tx_staffdirectory_backendModule:backend-module',
                    'text/javascript',
                    false,
                    false,
                    '',
                    true);

**Comment by bernhardberger** [comment]
Okay, it actually works if I include it via `$pageRenderer->addJsFile` (NOT as `footer`)

**Comment by sabbelasichon** [comment]
@bernhardberger At the moment, i have no idea what causes this issue. Would be nice, if you can figure this out.

**Comment by sabbelasichon** [comment]
@bernhardberger Could you find something? Maybe try the v1.4.1 release.

**Comment by bernhardberger** [comment]
Haven't had a chance to look at it yet. Currently a little bit tied up and for now I just wrapped it in jQuerys document ready..

**Comment by sabbelasichon** [comment]
Try to update to version 1.4.1. Maybe this helps. Thanks for your feedback.

**Comment by sabbelasichon** [comment]
I am going to close this issue for now. Feel free to reopen.
