### ISSUE TITLE
Add RTE configuration example in README

### ISSUE THREAD

**Issue by rintisch** [sabbelasichon/typo3_encore#146]
More by accident I realized that there is a solution for the generation of a CSS file for the RTE. This is imho totally worth to be described in the README. What do you think?

Something like 

### CSS for CKEditor 

It is possible to configure encore so that you can use a CSS file for the CKEditor which is generated by webpack and even works with enabled versioning.
Two steps are required to do so:

1. Define an entrypoint for the RTE in your `webpack.config.js`, e.g.
```js
Encore
    .addStyleEntry('rte', './assets/rte.scss')
```

2. Add in the CKEditor yaml configuration

```yaml
editor:
  config:
    contentsCss: "typo3_encore:rte"
```

**Comment by sabbelasichon** [comment]
Yes. Could you create a Pull Request?
