### ISSUE TITLE
Incompatibility with secure_downloads

### ISSUE THREAD

**Issue by jonasesr** [sabbelasichon/typo3_encore#15]
If a TYPO3 installation has bitmotion/secure-downloads installed and the file is requested to download by an user an exception is thrown.
`Asset manifest file "" does not exist.`
in /typo3conf/ext/typo3_encore/Classes/Asset/JsonManifestVersionStrategy.php line 79

It seems like the needed TypoScript is not included.

**Comment by sabbelasichon** [comment]
@jonasesr Could you provide more information. I just installed the extension bitmotion/secure-downloads and my test installation still works. Can download files

**Comment by sabbelasichon** [comment]
@jonasesr Could you tell me what version of typo3_encore and secure_downloads you are using.

**Comment by sabbelasichon** [comment]
@jonasesr The release https://github.com/sabbelasichon/typo3_encore/tree/v1.4.1 fix this problem. Please update.
