### ISSUE TITLE
Relative link with absRefPrefix where an absolute link would be needed

### ISSUE THREAD

**Issue by osw-mw** [sabbelasichon/typo3_encore#154]
We use the following setup:

```
Encore
  .setOutputPath(webRoot + buildPath)
  .setPublicPath('advance/' + buildPath)
```

and TypoScript setup

```
config.absRefPrefix = /advance/
```

In this case, EXT:typo3_encore wrongly generates relative links for CSS and JS assets (“advance/...”)

A possible workaround is `config.baseUrl = /` but this has side effects with link to local anchors insise the page.

We fixed the isse with the attached composer patch.
[absrefprefix-encore.txt](https://github.com/sabbelasichon/typo3_encore/files/9644042/absrefprefix-encore.txt)

**Comment by sabbelasichon** [comment]
@osw-mw Thanks. Will be fixed soon.
