### ISSUE TITLE
CSS for CKEditor with cms-composer-installers 4+ not working

### ISSUE THREAD

**Issue by Starraider** [sabbelasichon/typo3_encore#159]
Hi!
If I try to load the rte.css in the yaml file with
`
editor:
  config:
    contentsCss: "typo3_encore:rte"

`
I get an error: "The build "_default" is not configured".

The "rte.css" is generated correctly and the app.js and app.css are also loaded correctly.
The webpack.config.js looks like this:
`
 .addEntry('app', './js/app.js')
  .addStyleEntry('rte', './styles/rte.scss')
`
The TypoScript looks like this:
`
page {
  includeCSS {
    app = typo3_encore:app
  }
  includeJSFooterlibs {
    app = typo3_encore:app
  }
}
`
Only the "contentsCss: 'typo3_encore:rte'" in the yaml file, throws an error.
Any ideas, how to fix this?

CU...Sven

**Comment by sabbelasichon** [comment]
Did you check that you have assigned everything to the module section of the extension in TypoScript?

**Comment by sabbelasichon** [comment]
Good morning, what  i mean is, is the following line added to your TypoScript setup: https://github.com/sabbelasichon/typo3_encore/blob/master/Configuration/TypoScript/setup.typoscript#L21

Of course, i you have included everything from the extension it should work fine.

**Comment by Starraider** [comment]
Adding this Line 21 did fix my problem.
Thanks for your help!
Maybe you should mention this somewhere in the documentation, because this line can't be found there.
