### ISSUE TITLE
Settings for Dev Hotreload server

### ISSUE THREAD

**Issue by FaraFara** [sabbelasichon/typo3_encore#16]
For Dev Hotreload server i need set like this:
```
plugin.tx_typo3encore {
    settings {
        entrypointJsonPath = //dev.xxxxxx.com:8080/entrypoints.json
        manifestJsonPath = //dev.xxxxxx.com:8080/manifest.json
    }
}
```

By default this don't work.
How realize this idea?

Today iam use this hack:

```
[applicationContext == "Development"]
    page.includeJS {
        app = //dev.xxxxxx.com:8080/js/app.js
#       app = typo3_encore:app
        app.type = module
        app.external = 1
    }
    page.includeCSS {
    }
[end]
```

**Comment by sabbelasichon** [comment]
@FaraFara Never tried it, but check this out and try it: https://symfony.com/doc/current/frontend/encore/dev-server.html

If the extension can provide something useful for use this feature, i am willing to help.
