### ISSUE TITLE
TYPO3 12 only allow one contentsCss for RTE

### ISSUE THREAD

**Issue by websi** [sabbelasichon/typo3_encore#186]
With TYPO3 12 there is only one configuration option for `contentsCss` allowed.

See https://github.com/TYPO3/typo3/blob/0307a414cd8c77f8c6d4e703053e931e60146a99/typo3/sysext/rte_ckeditor/Classes/Form/Element/RichTextElement.php#L130 and https://forge.typo3.org/issues/99327

The handling of these option must be adjusted for TYPO3 12. https://github.com/sabbelasichon/typo3_encore/blob/master/Classes/Form/FormDataProvider/RichtextEncoreConfiguration.php#L52

**Comment by sabbelasichon** [comment]
@websi Thanks for the hint. Could you provide a fix for the different supported versions 10,11 and 12?

**Comment by websi** [comment]
Yes, we can provide a patch for that. But it will take a little while. Maybe in the next four weeks.

**Comment by websi** [comment]
Pull request is available. Please take a look. #187
