### ISSUE TITLE
[IDEA] Streamline Stimulus ViewHelpers with symfony/webpack-encore-bundle implementations

### ISSUE THREAD

**Issue by svenpet90** [sabbelasichon/typo3_encore#188]
First of all: Thank you so much for providing this extension!
Me myself am mainly working with symfony and loving the [symfony-ux](https://ux.symfony.com) ecosystem.

As "part time TYPO3 dev" I would love to also have these little helpers in a TYPO3 project, so I started to develop TYPO3 integrations for these packages - e.g. for [typo3-ux-vue](https://github.com/svenpet90/typo3-ux-vue) and [typo3-ux-react](https://github.com/svenpet90/typo3-ux-react)

When developing these extensions I saw that your implementations of the Stimulus-related ViewHelpers differs from the way that the symfony/webpack-encore-bundle Twig extensions work.

I therefore wrote my own [fluid-stimulus](https://github.com/svenpet90/fluid-stimulus) bridge in order so seamlessly integrate the UX-Packages.

Since having two packages doing basically the same thing is kinda pointless, I propose to create a PR changing the way your Stimulus VH work. Basically replacing your Stimulus VH implementations with mine/the way webpack-encore-bundle works.

This way:

1.) I can remove my EXT:fluid-stimulus crutch
2.) we would have EXT:typo3_encore as THE central part in implementing webpack-encore and all future symfony ux packages

What do you think? :-)

**Comment by sabbelasichon** [comment]
Yes, yes, yes. Would love to see your merge request.

**Comment by sabbelasichon** [comment]
Resolved by #189

**Comment by sabbelasichon** [comment]
@svenpet90 Thank you so much for taking care.
