### ISSUE TITLE
The build "_default" is not configured

### ISSUE THREAD

**Issue by Sm0ove** [sabbelasichon/typo3_encore#19]
Dear Sebastian,

I follwed your usage instructions step by step and I was able to run the encore command, outputting the compiled files. Unfortunately, when rendering the frontend of my TYPO3 site, an exception is thrown:

The build "_default" is not configured

Ssch\Typo3Encore\Asset\UndefinedBuildException thrown in file
/var/www/html/private/typo3conf/ext/typo3_encore/Classes/Asset/EntrypointLookupCollection.php in line 57.

Where has a "build" to be created and what does a "build" look like? Is it a folder or a file? I tried configuring it in the plugin settings and referencing to a EXT:EXTENSIONNAME/Resources/Public folder, but it still said that this build is not configured.

Thanks in advance,

Christian Rohleder

**Comment by sabbelasichon** [comment]
Which version are you using? And can you show me your TypoScript?

**Comment by sabbelasichon** [comment]
And could show me your webpack.config.js please.

**Comment by Sm0ove** [comment]
@sabbelasichon You can close this issue. I forgot to include the extension's TypoScript in the TypoScript template, my bad.

**Comment by sabbelasichon** [comment]
@Sm0ove Cool. That was easy. Hope you enjoy the extension and the frontend workflow.

**Comment by sabbelasichon** [comment]
@Sm0ove By the way i really like stars on github ;-)

**Comment by Mycl95** [comment]
Hi, I am using typo3 in a ddev container so I cannot install this via composer. I installed it by cloning (master bc I am using T3 10) into my ext folder. I get the same error message. I followed your steps.
