### ISSUE TITLE
Not working with RTE in a flexform

### ISSUE THREAD

**Issue by andreknieriem** [sabbelasichon/typo3_encore#195]
Hi there,

first of all: Thanks for this great extension! I've been using it now for a long time without any problems. Now I added a flexform to one content element with an rte. Your extension does not find them and doesn't replace the placeholder with the correct path to the css file.

I think a addition to Ssch\Typo3Encore\Form\FormDataProvider\RichtextEncoreConfiguration could help here, but Flexforms are sometimes very nested so I don't know where to start here.

To reproduce this you can use this flexform for example:
```xml
<T3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <TCEforms>
                    <sheetTitle>Einstellungen</sheetTitle>
                </TCEforms>
                <type>array</type>
                <el>
                    <settings.test>
                        <TCEforms>
                            <label>Text</label>
                            <config>
                                <type>text</type>
                                <enableRichtext>1</enableRichtext>
                                <richtextConfiguration>myext_default</richtextConfiguration>
                            </config>
                        </TCEforms>
                    </settings.test>
                </el>
                    </settings.headlines>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</T3DataStructure>
```

**Comment by sabbelasichon** [comment]
@andreknieriem Thanks for your feedback. Good things come to those who wait. I found some time today to dig into your problem and i guess i have found the reason for it.

**Comment by sabbelasichon** [comment]
@andreknieriem Could you please add the following to your Configuration to try it out: 

`php
$GLOBALS['TYPO3_CONF_VARS']['SYS']['formEngine']['formDataGroup']['flexFormSegment'][\Ssch\Typo3Encore\Form\FormDataProvider\RichtextEncoreConfiguration::class] = [
    'depends' => [\TYPO3\CMS\Backend\Form\FormDataProvider\TcaText::class],
];
`
