### ISSUE TITLE
Missing / with USER_INT on page

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3_encore#211]
It seems this issue is a core issue, nevertheless would like to add this as issue here as well..

Using TYPO3 12 + latest typo3_encore

Got a strange issue regarding caching and including files.

if there is a USER_INT/COA_INT on a page, the first uncached page got

```html
<link rel="stylesheet" href="/build/app.css?1696319881" media="all">
```

```html
<link rel="stylesheet" href="build/app.css?1696319881" media="all">
```

which breaks the frontend if no `config.baseURL = /` is set.

**Comment by sabbelasichon** [comment]
@georgringer How can we fix this issue? Any suggestions

**Comment by georgringer** [comment]
no not really. if you can reproduce it, I suggest to create an issue at forge and ask in coredev for additional help
