### ISSUE TITLE
Error with Asset Viewhelper linking assets from extension in TYPO3 12

### ISSUE THREAD

**Issue by SvenJuergens** [sabbelasichon/typo3_encore#228]
hi, I have upgraded a composer installation from 11 to 12. Now the linking of files from extensions does not work anymore.

In TYPO3 11 the link was correct:
typo3conf/ext/my_extension/Resources/Icons/myImage.jpg

in TYPO3 12 I get:
/xxx/my-extesion/Resources/Public/Icons/myImage.jpg

but this should be correct link
_assets/ccfef66b7e44f557753bd7c63c152e53/Icons/myImage.jpg

In this migration https://docs.typo3.org/m/typo3/guide-installation/12.4/en-us/MigrateToComposer/AssetMigration.html Doc it is recommended to generate the paths like this:

`PathUtility::getAbsoluteWebPath(GeneralUtility::getFileAbsFileName('EXT:my-extension/Resources/Public/logo.jpg')`
is it possible to integrate this for TYPO3 12 for links with 'EXT:my_extenison...' links?

Best Regards
Sven

**Comment by sabbelasichon** [comment]
@SvenJuergens I suggest to move your assets to a folder outside of your extension. Have a look at: https://github.com/sabbelasichon/typo3_encore?tab=readme-ov-file#working-with-typo3cms-composer-installers-4-or-typo3-12
