### ISSUE TITLE
Release version doesn't match emconf version

### ISSUE THREAD

**Issue by schliesser** [sabbelasichon/typo3_encore#36]
The latest release is called v2.0.9 and comes with `'version' => '2.2.0',` in the ext_emconf.php file.
Also the previous version v2.0.8 doesn't match the emconf version. That's confusing. It would be great if they match in future.

**Comment by sabbelasichon** [comment]
@schliesser Of course. Thanks for your feedback.

**Comment by sabbelasichon** [comment]
@schliesser By the way: I really love stars on github ;-)

**Comment by sabbelasichon** [comment]
This version numbers are now consistent.
