### ISSUE TITLE
Add link header for cached pages

### ISSUE THREAD

**Issue by codemonkey1988** [sabbelasichon/typo3_encore#42]
The link header is currently not passed when the page is generated from cache.

Steps to reproduce:

1. Make sure that the link header is added to the response headers after clearing the TYPO3 cache
2. Make sure the page is cacheable
3. Call cached page in frontend and check the response headers. No link header is available.

**Comment by sabbelasichon** [comment]
Resolved by #43

**Comment by sabbelasichon** [comment]
Resolved by #43
