### ISSUE TITLE
Different namespace for viewhelpers

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3_encore#53]
I propose a different namespace for the viewhelpers by default. instead of `e` use `encore`.

advantages:
- more speaking
- less guessing

as those VH are not used that often in a project, the additional chars are IMO fine

**Comment by sabbelasichon** [comment]
@georgringer Do you mean in the README.md? Because you can define the namespace individually.

**Comment by georgringer** [comment]
Yes Readme. Of course someone can change it but we should move away from those one char namespace (n:... Haha)
