### ISSUE TITLE
Add compatibility for version 11

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3_encore#62]

**Comment by andyhausmann** [comment]
As far as I can tell, only File 

`Classes/Integration/PageRendererHooks.php`

seems incompatible.

In line 71 you can find

```$position = ($jsFile['section'] ?? '') === PageRenderer::PART_FOOTER ? TagRenderer::POSITION_FOOTER : '';```

where `PageRenderer::PART_FOOTER` is not accessible anymore due to its new protected declaration.

My temp fix would be to change it to:

```$position = ($jsFile['section'] ?? '') === 2 ? TagRenderer::POSITION_FOOTER : '';```

**Comment by sabbelasichon** [comment]
@andyhausmann I am on it. There is one more in the middleware. Everything should be fine.
