### ISSUE TITLE
Error on parsing new structure entrypoints.json

### ISSUE THREAD

**Issue by FaraFara** [sabbelasichon/typo3_encore#69]
Since version 4 webpack-assets-manifest generate new structure:

⚠️ The structure of the entrypoints data has been updated to include preload and prefetch assets. **Assets for an entrypoint are now included in an assets property under the entrypoint.**

Example:

{
  "entrypoints": {
    "main": {
      **"assets": {**
        "css": [
          "main.css"
        ],
        "js": [
          "main.js"
        ]
      },
      "prefetch": {
        "js": [
          "prefetch.js"
        ]
      },
      "preload": {
        "js": [
          "preload.js"
        ]
      }
    }
  }
}

And typo3_encore don't parse this:

page.includeJS {
  main = typo3_encore:main
}
 page.includeCSS {
        main = typo3_encore:main
 }

**Comment by sabbelasichon** [comment]
@FaraFara Do not know what you mean? Webpack Encore is not using webpack-assets-manifest.

**Comment by FaraFara** [comment]
I am using custom webpack configs (not Encore).
"assets-webpack-plugin" generate entrypoint.json without "entrypoins" key:
`{
    "app": {
        "js": [
            "/js/runtime.924a11e4c30cd5be355a.js",
            "/js/app.047581870e05ad5edf3d.js"
        ],
        "css": [
            "/css/styles.21ed731805973f9eba13.css",
            "/css/app.21ed731805973f9eba13.css"
        ]
    },
    "rte": {
        "js": [
            "/js/runtime.924a11e4c30cd5be355a.js",
            "/js/rte.26322386e94156148a33.js"
        ],
        "css": "/css/rte.21ed731805973f9eba13.css"
    }
}
`
typo3_encore generate exception

Can i use some option in typo3_encore to use without "entrypoints" key in json file?

**Comment by sabbelasichon** [comment]
@FaraFara This extension is created for Webpack Encore. So the straight answer would be no. But you are still able to create your own concrete implementation of the EntryPointLookupInterface https://github.com/sabbelasichon/typo3_encore/blob/master/Classes/Asset/EntrypointLookupInterface.php.
