### ISSUE TITLE
HTTP/2 Push not working when using TYPO3 versioning

### ISSUE THREAD

**Issue by moe2k** [sabbelasichon/typo3_encore#7]
This issue is only related to dev-master.

When using `$GLOBALS['TYPO3_CONF_VARS']['FE']['versionNumberInFilename'] = 'querystring'`, the frontend links assets with a version number added as query string. Since typo3-encore's middleware does not have the query string information at hand when creating the `link` HTTP-header, it's missing there. Thus, after downloading the document, the browser then loads the linked resource from the document, in addition to the pushed one because it treats them as two files.

In turn, disabling TYPO3 versioning in conjunction with active webpack versioning (changing  filename) leads to problems with missing assets when using long-lasting (24h) document caching policies, because assets linked in the cached document are not available anymore on the server.

So ideally TYPO3 versioning by query string should be regarded when creating the push link. Or it must be disabled but then cannot not be used in conjunction with document caching.

**Comment by sabbelasichon** [comment]
@moe2k Thanks, i will have look into it. Why are you having issues with missing files. Should stay the same as long as you don´t change them. How did you enable the versioning?

**Comment by moe2k** [comment]
Thanks a lot! 

Versioning was enabled in webpack config like this, with default filenames.
`.enableVersioning(Encore.isProduction())`

Of course files are only re-generated / missing once they are changed, so to speak when a deployment happens. When a User then requests an old asset, initiated by his (outdated) html document, that asset is missing.

(Though, I was wondering why the old asset gets requested at all, because it should also have been taken from user's browser cache as it was saved at the same time as the document. But that's another story to investigate for me).

**Comment by sabbelasichon** [comment]
@moe2k Tell me if it is now working for you. If not, reopen the issue. Thanks for your feedback. I really appreciate it.
