### ISSUE TITLE
Add a way to include css endpoint as inline css

### ISSUE THREAD

**Issue by kszymukowicz** [sabbelasichon/typo3_encore#71]
hi

A question:  is there a way to put some css endpoint as inline_css? 

Why?

REASON 1:
The reason is the Google PageSpeed Insights test called "Preload key requests". Its telling about font preload.
I know I can use` <link rel=preload>` or push the fonts with `http2` headers (I use it for woff2)
 
Unfortunately the problem is that Google PageSpeed Insights is also requesting other font types to be preloaded like woff, ttf, eof. This has no big sense to download all this font types if browser use only one. 

I noticed that if I put in `<head>` a `<style>` with font-face definitions then Google PageSpeed Insights no longer require to preload any fonts. That has some sense because the information what to download is on the very beginning of HTML - no css file needs to be downloaded to start to download right font file.

REASON 2:
Sometimes there is a need to have critical inline css to draw a content as fast as possible (menu, header elements) to have good score on First Contentful Paint (FCP).

btw: thank you for this nice extension.

**Comment by kszymukowicz** [comment]
btw: I did test to push small css file with http2. In this css file there were only font-face definition. Still Google PageSpeed Insights wanted to "Preload key requests" for fonts.

**Comment by sabbelasichon** [comment]
@kszymukowicz Fixed the issue behind the scenes. You can now still use the leading slash in your webpack.config.js but it is removed if you want to inline it.

**Comment by kszymukowicz** [comment]
Everything is working as expected in v3.0.2 of typo3_encore. 
Tnx a lot!
