### ISSUE TITLE
Viewhelper to generate Preload-Links to generated fonts

### ISSUE THREAD

**Issue by moe2k** [sabbelasichon/typo3_encore#8]
I would like to create preload links in my page's `<head>` to preload e.g. fonts which are deeply nested within my CSS and would therefore be loaded quite late. 

Example:
`<link rel="preload" href="fonts/cicle_fina-webfont.woff2" as="font" type="font/woff2" crossorigin>`
(taken from [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Cross-origin_fetches))

Unfortunately when using webpack-encore in production mode, font files are versioned, so the path to the built font asset cannot be hard-coded.

That's why it would be very useful to have a ViewHelper which I could feed e.g. the original file path and then it looks up the actual path to the built font and renders the link tag dynamically.

Note: Currently, as a workaround, I disabled versioning for fonts in my webpack.config to be able to hard-code preload tags.
```
    // disable versioning for fonts to allow preloading
    .configureFilenames({
        fonts: 'fonts/[name].[ext]'
    })
```

**Comment by sabbelasichon** [comment]
@moe2k This is a nice idea and should be doable via manifests.json file. But i would like to have a deeper look and would like to create a registry for that, so we can streamline the Preloading for all assets.

**Comment by moe2k** [comment]
That'd be perfect!

**Comment by sabbelasichon** [comment]
@moe2k Would be nice if you can check this out. Also described this new feature here: https://github.com/sabbelasichon/typo3_encore#http2-preloading

**Comment by moe2k** [comment]
Thanks a lot! Basically it does what I need. I ran into the issue though that the `e:asset` viewhelper did not properly resolve my file. The Path in the final tag always gets rendered as is. 

Input: 
`{e:asset(pathToFile: 'typo3conf/provider/Resources/Public/Fonts/Open_Sans/OpenSans-Bold.ttf')}`

Output: 
`typo3conf/provider/Resources/Public/Fonts/Open_Sans/OpenSans-Bold.ttf`

No matter if using EXT: keyword or relative paths.

Is my assumption correct that the input path here should be the "original" asset, and the output should be the built one? I am wondering how encore is supposed to resolve the build asset because in my manifest.json there is no such mapping information at all:
```
{
"typo3conf/ext/con_provider/Resources/Public/Build/fonts/OpenSans-Bold.ttf": "/typo3conf/ext/con_provider/Resources/Public/Build/fonts/OpenSans-Bold.ttf"
}
```

As a side note: I want to use HTTP Preload, not HTTP/2 Push.

https://www.keycdn.com/blog/http-preload-vs-http2-push#when-to-use-preload-vs-push

Your documentation reads:

`<e:preload attributes="{type: 'font/woff2'}" as="font" uri="{e:asset(pathToFile: 'EXT:typo3_encore/Resources/fonts/webfont.woff2')}" />
`
What this VH does is that it adds a preload header for http/2 push alongside the document:

`</EXT:typo3_encore/Resources/fonts/webfont.woff2>; rel="preload"; as="font"; type="font/woff2",`

While that should be fine for most cases, I just wanted to render a <link rel="preload"> tag in the `<head>` section of my document like this:
`<link rel="preload" href="fonts/webfont.woff2" as="font" type="font/woff2" crossorigin>`

So actually I want to use the `e:asset` viewhelper in conjunction with a viewhelper from EXT:VHS:

`<v:page.header.link rel="preload" href="{e:asset(pathToFile: 'EXT:typo3_encore/Resources/fonts/webfont.woff2')}" additionalAttributes="{as: 'font/woff2', crossorigin: true}"/>`

**Comment by sabbelasichon** [comment]
@moe2k How do you reference your fonts? If i include them in my css which is managed by webpack the file is also included in the manifest.json. If this is the case, the path will be resolved. In your case you get the input as output. That is intended by my programming code. Of course, i could throw also an exception. Maybe this is more transparent.

So, you have to investigate why your font files are not in the manifest.json file.

**Comment by colorcube** [comment]
> @moe2k How do you reference your fonts? If i include them in my css which is managed by webpack the file is also included in the manifest.json. If this is the case, the path will be resolved. In your case you get the input as output. That is intended by my programming code. Of course, i could throw also an exception. Maybe this is more transparent.

I think this should be mentioned in the 'HTTP/2 Preloading' readme section. I stumbled across the same problem and thought it may be a bug.

**Comment by colorcube** [comment]
still no luck with resolving EXT:

- fonts are imported in scss
- build with encore/webpack
- fonts are copied to Assets/fonts
- fonts are in manifest.json

not really a big deal because I can write /typo3conf/ext/ instead of EXT :-)

**Comment by sabbelasichon** [comment]
@colorcube Thanks for the feedback. I have fixed this minor issue. Now you can also use EXT: in the AssetViewHelper. If you have more suggestions let me know. If you like this tiny extension spread the word via twitter or somewhere else.
