### ISSUE TITLE
Disable JavaScript type attribute for html5 doctype in Fluid templates

### ISSUE THREAD

**Issue by Kephson** [sabbelasichon/typo3_encore#80]
If there is the TypoScript setting config.doctype = html5 we don't want to have the type 'text/javascript' in the script tags.
It works fine via TypoScript including of JS files, but not when using the ViewHelper inside Fluid templates to include scripts.

**Comment by sabbelasichon** [comment]
@Kephson I assume everyone is using html5 nowadays, right? Just drop the type.

**Comment by Kephson** [comment]
I think we could drop the type, but I don't know if somebody is using other doctypes together with typo3_encore...
