### ISSUE TITLE
Document the cache

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3_encore#83]
thanks for the extension! one thing should be highlighted in the docs is the usage of the caching framework. switching different modes like dev, hotreload, production on same environment will lead to a broken frontend because the cache will still hold the previous paths which won't exist anymore.

One option is to use
```php

$GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'][\Ssch\Typo3Encore\Integration\CacheFactory::CACHE_KEY]['backend'] = \TYPO3\CMS\Core\Cache\Backend\NullBackend::class;
```

or maybe even remove the cache completly? as it is a filecache anyway I don't see much benefits in getting the real entrypoint file or the file from the caching framework?

**Comment by sabbelasichon** [comment]
Totally agree. I am gonna remove it. It is only useful if you are using an in memory cache like redis or memcached.

**Comment by sabbelasichon** [comment]
Actually it stayed there since the beginning and i forgot about it
