### ISSUE TITLE
Order of includes changes when mixing typo3_encore and normal includes

### ISSUE THREAD

**Issue by rvock** [sabbelasichon/typo3_encore#88]
When I have two CSS files on a page, the order is different when the first is included via typo3_encore and the other via TYPO3.

TypoScript without typo3 encore:

```typoscript
page {
	includeCSS {
		example = EXT:example/Resources/Public/static/example1.css
		example.disableCompression = 1
		example.excludeFromConcatenation = 1

		example2 = EXT:example/Resources/Public/static/example2.css
		example2.disableCompression = 1
		example2.excludeFromConcatenation = 1
	}
}
```

Output in HTML:
```html
<link rel="stylesheet" href="/static/example1.css?1621689390">
<link rel="stylesheet" href="/static/example2.css?1621689423">
```

When the first CSS is included via typo3_encore:
```typoscript
page {
	includeCSS {
		example = typo3_encore:example1
		example = EXT:example/Resources/Public/static/example1.css
		example.disableCompression = 1
		example.excludeFromConcatenation = 1

		example2 = EXT:example/Resources/Public/static/example2.css
		example2.disableCompression = 1
		example2.excludeFromConcatenation = 1
	}
}
```

Now the order is different:
```html
<link rel="stylesheet" href="/static/example2.css?1621689423">
<link rel="stylesheet" href="/static/example1.css">
```

This might break stuff, because the order is important.

This happens, because the `PageRendererHooks::renderPreProcess` adds the files at the end of the array instead of replacing the key.

The error also occurs with JavaScript files.

**Comment by rvock** [comment]
I've added a commit in my fork, but the TagRendererTest still has errors. I am not sure, if my fix is incorrect or if the testcase needs adjustments. Should I still open a Pull-Request?

**Comment by sabbelasichon** [comment]
Could you close the issue

**Comment by rvock** [comment]
Do you mean, if I was able to fix the issue?
Yes, the order of the included files is correct with my commit. But the testcases still have errors. That's why I haven't opened a pull request with this commit.

**Comment by sabbelasichon** [comment]
I am gonna fix the tests

**Comment by sabbelasichon** [comment]
Everything seems fine. The failing test is unrelated to your change. I am not sure but the database connection is fragile from time to time so the functional tests are not running successfully.

**Comment by rvock** [comment]
Sorry, but you closed the issue, but did not merge the commit: https://github.com/rvock/typo3_encore/commit/db7c74941822fd96759e68c48a2b97e50f38c743

This bug is not yet fixed in master.

**Comment by sabbelasichon** [comment]
Oh. I thought it was related to the other Pull Request. In that case you should do a Pull Request first. Then i can see the failing tests here

**Comment by sabbelasichon** [comment]
@rvock Could you send your Pull Request again please. I would like to fix this issue because i think it is a valid use case. Sorry for being so late at the party.
