### ISSUE TITLE
allWrap should wrap all files for a single entrypoint

### ISSUE THREAD

**Issue by rvock** [sabbelasichon/typo3_encore#91]
If I am using `allWrap` to wrap an entrypoint I might expect that the wrap is only generated once and wraps all script tags for a single entrypoint. That is currently not the case:

```
page {
    includeJS {
        example = typo3_encore:example1
        example.disableCompression = 1
        example.excludeFromConcatenation = 1
        example.allWrap = <!-- Before -->|<!-- After -->
    }
}
```

Generated HTML:
```html
<!-- Before --><script src="/static/runtime.js"></script><!-- After -->
<!-- Before --><script src="/static/example1.js"></script><!-- After -->
```

Expected HTML:
```html
<!-- Before --><script src="/static/runtime.js"></script>
<script src="/static/example1.js"></script><!-- After -->
```

This could be achieved, if the `allWrap` is split up into two parts and the first part is applied to the first script tag and the second part is applied to the last script tag like this:
```
page {
    includeJS {
        runtime = static/runtime.js
        runtime.disableCompression = 1
        runtime.excludeFromConcatenation = 1
        runtime.allWrap = <!-- Before -->|

        example1 = static/example1.js
        example1.disableCompression = 1
        example1.excludeFromConcatenation = 1
        example1.allWrap = |<!-- After -->
    }
}
```

**Comment by sabbelasichon** [comment]
Never used it in this context. For what it is useful in your case?  Because behind the scenes every file from the entrypoint is added separately. Could imagine to hack this, but would prefer not to do so. So, what is your requirement here?

**Comment by rvock** [comment]
We are wrapping the script tag to get performance measurements:

```
example1 = static/example1.js
example1.disableCompression = 1
example1.excludeFromConcatenation = 1
example.allWrap = <script>performance.mark('script:block');</script>|<script>performance.mark('script:unblock');</script>
```

This resulted in the following HTML (when only one file was used before using webpack):
```html
<script>performance.mark('script:block');</script>
<script src="/static/example1.js"></script>
<script>performance.mark('script:unblock');</script>
```

This means, we get two performance measurements for that script: One just before the script starts and will block loading and one after the script has been executed.

When webpack and typo3-encore are used the resulting HTML looks like this (linebreaks added for better readability):
```html
<script>performance.mark('script:block');</script>
<script src="/static/runtime.js"></script>
<script>performance.mark('script:unblock');</script>

<script>performance.mark('script:block');</script>
<script src="/static/example1.js"></script>
<script>performance.mark('script:unblock');</script>
```

Now we get four measurements instead of two.

**Comment by sabbelasichon** [comment]
Thanks. Looks interesting. Any ideas how to tackle this? As i said, behind the scenes every file of an entrypoint is added independently.

**Comment by rvock** [comment]
Currently the script tags are added by the method [TagRenderer::renderWebpackScriptTags](https://github.com/sabbelasichon/typo3_encore/blob/9cec2d4ba64a8b6ffbaaed4fb6fdf2a1467a4c63/Classes/Asset/TagRenderer.php#L75).

There the `allWrap` must be split into two parts. The first part should be added to the first script tag, the second part to the last script tag. This would change `<!-- Before -->|<!-- After -->` to `<!-- Before -->|` for the first script tag and `|<!-- After -->` for the second script tag.

I can send a pull request to do this. But my other pull request (#92 ) changes the same code part and I would wait until it is merged.

**Comment by sabbelasichon** [comment]
Looks like the way to go. Go for it
