### ISSUE TITLE
Specific configuration may break css classes

### ISSUE THREAD

**Issue by codemonkey1988** [sabbelasichon/typo3_encore#97]
TYPO3 version: 10.4.18
Ext. version: 3.0.9

A maybe common configuration of this ext might lead to adding "/" prefix to attribute values.
Assuming there is an encore config that writes files to the js/ directory (see example below) inside the Resources/Public folder. When there is a css class named "js-toggle", that class would become "/js-toggle".
This is because of the `Ssch\Typo3Encore\Asset\TagRenderer::addAdditionalAbsRefPrefixDirectories` method.
I'm not quite sure, what this method should actually archive (except the obvious adding the relative path to additionalAbsRefPrefixDirectories) so I cannot provide a fix for this.

Steps to reproduce:
1. Configure to write a JavaScript file to Resources/Public/js 
2. Add a class attribute so some element and put "js-toggle" in it (it needs to be the first class in it)
3. When calling the page in the frontend, the class attribute will look like `class="/js-toggle"`

Example webpack configuration:
```javascript
const Encore = require('@symfony/webpack-encore');
if (!Encore.isRuntimeEnvironmentConfigured()) {
  Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}
Encore
    .setOutputPath('packages/site/Resources/Public')
    .setPublicPath('/typo3conf/ext/site/Resources/Public')
    .setManifestKeyPrefix('');
Encore.addEntry('js/app', './packages/site/Resources/Private/Build/js/app.js');
module.exports = Encore.getWebpackConfig();
```

**Comment by sabbelasichon** [comment]
@Tobi77 Could you please check if we could change this behaviour. The problem was introduced here: https://github.com/sabbelasichon/typo3_encore/pull/82/
